[package]
name = "ecs"
license = "MIT OR Apache-2.0"
version = "0.0.0"
edition = "2024"

[dependencies]
assets.workspace = true
bvh.workspace = true

anyhow.workspace = true
bevy_ecs.workspace = true
macroquad.workspace = true
rapier2d.workspace = true
tracing.workspace = true
