[package]
name = "roketz"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
dirs = "6.0.0"
pixels = "0.15.0"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.23"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
winit = "0.30.11"
