[package]
name = "roketz"
version = "0.1.0"
edition = "2024"

[dependencies]
assets = { path = "assets_crate" }
rasset = "1.0.0-beta.1"
anyhow = "1.0.98"
dirs = "6.0.0"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.23"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tracing-appender = "0.2.3"
macroquad = "0.4.14"

[build-dependencies]
assets = { path = "assets_crate", features = ["declare"] }
