[workspace]
resolver = "2"
members = [
  "crates/proc_macros",
  "crates/utils",
  "roketz",
]

[profile.release]
strip = "symbols"

[workspace.dependencies]
# Workspace members
roketz = { path = "roketz" }
utils = { path = "crates/utils" }
proc_macros = { path = "crates/proc_macros" }
# Rendering and engine
bevy_ecs = "0.16.1"
egui = "0.31.1"
rapier2d = { version = "0.26.1", features = ["simd-stable"] }
# Config/data formats
bincode = "2.0.1"
knus = "3.3.1"
miette = { version="7.2.0", features=["fancy"] }
rdss = "0.2.0"
ron = "0.10.1"
serde = { version = "1.0.219", features = ["derive"] }
# Supporting libs
anyhow = "1.0.98"
criterion = "0.5"
crossbeam = "0.8.4"
dirs = "6.0.0"
main_error = "0.1.2"
nix = { version = "0.30.1", features = ["signal"] }
signal-hook = "0.3.18"
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

# [profile.dev.package.rapier2d]
# opt-level = 3
#
# [profile.release.package.rapier2d]
# codegen-units = 1
#
# [profile.dev.package.bevy_ecs]
# opt-level = 3
#
# [profile.release.package.bevy_ecs]
# codegen-units = 1
