[package]
name = "roketz"
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2024"

[dependencies]
assets = { path = "assets_crate" }
rasset = "1.0.0-beta.1"
anyhow = "1.0.98"
dirs = "6.0.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tracing-appender = "0.2.3"
serde = { version = "1.0.219", features = ["derive"] }
ron = "0.10.1"
macroquad = "0.4.14"
egui = "0.31.1"
egui-macroquad = "0.17.3"
egui_inspect = "0.1.3"
nix = { version = "0.30.1", features = ["signal"] }
signal-hook = "0.3.18"
bevy_ecs = "0.16.1"

[build-dependencies]
assets = { path = "assets_crate", features = ["declare"] }

[dev-dependencies]
criterion = "0.5"
thiserror = "1.0"
proptest = "1.4"
mockall = "0.12"
tempfile = "3.10"

[[bench]]
name = "bvh"
harness = false
