[build.env]
passthrough = [
    "FMOD_SYS_FMOD_DIRECTORY",
]

[target.x86_64-unknown-linux-gnu]
pre-build = [
    "apt-get update -y",
    "apt-get install -y pkg-config libx11-dev libxi-dev libgl1-mesa-dev libasound2-dev"
]

