[graph]
targets = []
all-features = false
no-default-features = false

[output]
feature-depth = 1

[advisories]
ignore = [
    "RUSTSEC-2025-0035",
    "RUSTSEC-2024-0436",
]

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
]

confidence-threshold = 0.8
exceptions = [
    { allow = ["Zlib"], name = "foldhash" },
    { allow = ["MPL-2.0"], name = "option-ext" },
    { allow = ["Unicode-3.0"], name = "unicode-ident" },
    { allow = ["BSL-1.0"], name = "clipboard-win" },
    { allow = ["BSL-1.0"], name = "error-code" },
    { allow = ["OFL-1.1", "Ubuntu-font-1.0"], name = "epaint_default_fonts" },
    { allow = ["ISC"], name = "libloading" },
    { allow = ["BSD-3-Clause"], name = "ogg" },
    { allow = ["MPL-2.0"], name = "lanyard" },
    { allow = ["MPL-2.0"], name = "fmod-oxide" },
    { allow = ["MPL-2.0"], name = "fmod-audio-sys" },
    { allow = ["BSD-3-Clause"], name = "bindgen" },
]

[licenses.private]
ignore = false
registries = []

[bans]
multiple-versions = "allow"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []
deny = [
    "serde_yml",
    "libyml",
    "vrd",
    "rlg",
    "dtt",
    "ssg",
    "libmake",
    "xtasks",
    "hsh",
    "mini-functions",
]
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
