use anyhow::{Context, Result};
use std::{io::Write, sync::LazyLock};

const ROOT: &str = "../..";

macro_rules! relative_path {
    ($name: ident, $path: expr) => {
        static $name: LazyLock<String> = LazyLock::new(|| format!("{}/{}", ROOT, $path));
    };
}

macro_rules! path {
    ($name: expr) => {
        &(*$name)
    };
}

#[cfg(feature = "fmod")]
relative_path!(BANKS_DEST, "assets/sound");
relative_path!(BANKS_BINDINGS, "crates/sound/src/codegen/bindings.rs");

fn main() {
    if let Err(e) = try_main() {
        eprintln!("Error: {:?}", e);
        std::process::exit(1);
    }
}

fn try_main() -> Result<()> {
    generate_fmod_bindings().context("Failed to generate FMOD Bank bindings")?;
    println!("cargo:rerun-if-changed={}", path!(BANKS_BINDINGS));

    Ok(())
}

fn generate_fmod_bindings() -> Result<()> {
    let path = std::path::PathBuf::from(path!(BANKS_BINDINGS));
    let dir = path
        .parent()
        .context("Failed to get parent directory for bindings file")?;
    std::fs::create_dir_all(dir).context(format!(
        "Failed to create directory for bindings file at {}",
        dir.display()
    ))?;
    let mut file = std::fs::File::create(path!(BANKS_BINDINGS)).context(format!(
        "Failed to create bindings file at {}",
        path!(BANKS_BINDINGS)
    ))?;

    file.write_all(b"// This file is generated by the build script. Do not edit manually.\n\n")
        .context("Failed to write header to bindings file")?;
    #[cfg(not(feature = "fmod"))]
    file.write_all(b"// FMOD feature is disabled. Enable it ro generate bindings\n")
        .context("Failed to write feature comment to bindings file")?;

    #[cfg(feature = "fmod")]
    {
        use fmod::Utf8CStr;

        let builder = unsafe { fmod::studio::SystemBuilder::new() }
            .context("Failed to create FMOD system builder")?;
        let system = builder
            .build(
                128,
                fmod::studio::InitFlags::NORMAL,
                fmod::InitFlags::NORMAL,
            )
            .context("Failed to build FMOD system")?;

        let bank_dir = std::path::PathBuf::from(path!(BANKS_DEST));

        let mut banks: Vec<_> = std::fs::read_dir(&bank_dir)?
            .filter_map(|entry| {
                let path = entry.ok()?.path();
                if path.extension().and_then(|e| e.to_str()) == Some("bank") {
                    Some(path)
                } else {
                    None
                }
            })
            .collect();

        // Sort .strings.bank before other banks
        banks.sort_by_key(|path| {
            let name = path.file_name().unwrap_or_default().to_string_lossy();
            if name.contains(".strings") {
                0
            } else {
                1
            }
        });

        for path in banks {
            let cstring = std::ffi::CString::new(path.to_string_lossy().to_string())?;
            let bank_path: &Utf8CStr = Utf8CStr::from_cstr(&cstring)?;
            let bank = system.load_bank_file(bank_path, fmod::studio::LoadBankFlags::NORMAL)?;
            let events = bank.get_event_list()?;

            if !events.is_empty() {
                writeln!(
                    file,
                    "// {}",
                    path.file_name().unwrap_or_default().to_string_lossy()
                )?;
            }

            for event in events {
                let event_path = event.get_path()?;
                let event_name = event_path
                    .clone()
                    .replace(":", "")
                    .replace("/", "_")
                    .to_uppercase();
                writeln!(file, "pub const {}: &str = \"{}\";", event_name, event_path)?;
            }

            println!("cargo:rerun-if-changed={}", path.display());
        }
    }

    Ok(())
}
