[package]
name = "roketz"
license = "MIT OR Apache-2.0"
version = "0.0.1"
build = "build.rs"
edition = "2024"

[dependencies]
assets.workspace = true
config.workspace = true
ecs.workspace = true

anyhow.workspace = true
bevy_ecs.workspace = true
dirs.workspace = true
egui-macroquad.workspace = true
egui.workspace = true
macroquad.workspace = true
nix.workspace = true
rapier2d.workspace = true
rasset.workspace = true
ron.workspace = true
serde.workspace = true
signal-hook.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true

[build-dependencies]
assets = {path = "../../crates/assets", features = ["declare"] }
anyhow.workspace = true
