[package]
name = "roketz"
license = "MIT OR Apache-2.0"
version = "0.0.1"
build = "build.rs"
edition = "2024"

[features]
default = []
fmod = ["sound/fmod", "ecs/fmod", "fmod-oxide"]

[dependencies]
bvh.workspace = true
ecs.workspace = true
sound = { path = "../../crates/sound", default-features = false, optional = true }

anyhow.workspace = true
bevy_ecs.workspace = true
dirs.workspace = true
egui-macroquad.workspace = true
egui.workspace = true
macroquad.workspace = true
nix.workspace = true
rapier2d.workspace = true
rdss.workspace = true
ron.workspace = true
serde.workspace = true
signal-hook.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true

[build-dependencies]
anyhow.workspace = true
rdss.workspace = true
fmod-oxide = { version = "0.2.0", optional = true }
