name: CI

on:
  push:
    branches: [main, mvp]
  pull_request:
    branches: [main, mvp]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Format
        run: cargo fmt -- --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install Clippy
        run: rustup component add clippy
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y \
          libx11 libasound2 libudev libgl1-mesa pkg-config build-essential
      - name: Build
        run: cargo build --verbose
      - name: Run test
        run: cargo test --verbose
