name: CI

on:
  push:
    branches: [main, mvp]
  pull_request:
    branches: [main, mvp]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Format
        run: cargo fmt -- --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install pkg-config libx11-dev libxi-dev libgl1-mesa-dev libasound2-dev
      - name: Install Clippy
        run: rustup component add clippy
      - name: Run clippy
        run: cargo test --verbose --workspace --no-default-features --all-targets -p roketz --features="" -p ecs --features="" -p sound --features="" -- -D warnings

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install pkg-config libx11-dev libxi-dev libgl1-mesa-dev libasound2-dev
      - name: Build
        run: cargo build --workspace --no-default-features --all-targets -p roketz --features="" -p ecs --features="" -p sound --features=""
      - name: Run test
        run: cargo test --workspace --verbose --no-default-features --all-targets -p roketz --features="" -p ecs --features="" -p sound --features=""

  deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install cargo-deny
        run: cargo install cargo-deny --locked
      - name: Run cargo deny
        run: cargo deny check
